name: Android Build

on:
  push:
    branches:
      - main
      - foundation-v0.1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission
        run: |
          if [ -f gradlew ]; then chmod +x gradlew; fi

      - name: Show Project
        run: ls -R

      - name: Build APK
        run: |
          if [ -f gradlew ]; then
            ./gradlew assembleDebug
          else
            echo "Gradle Wrapper Missing"
            exit 1
          fi

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: SuryaLiveStudio-debug
          path: app/build/outputs/apk/debug/*.apk
